# Generated by Django 4.0.3 on 2022-03-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['date_added']},
        ),
    ]
