# Generated by Django 4.0.3 on 2022-03-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
