# Generated by Django 4.0.3 on 2022-03-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_category_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='annotation',
        ),
    ]
