# Generated by Django 4.0.3 on 2022-03-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_appuser_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='deleted_at',
        ),
    ]
