# Generated by Django 4.0.3 on 2022-03-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_remove_appuser_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
