# Generated by Django 4.0.3 on 2022-03-17 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must not consist of space and requires country code. eg: +6591258565', regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}')]),
        ),
    ]
